from typing import Protocol


class CatalogServiceInterface(Protocol):
    def get_datasets(self) -> list[dict[str, object]]: ...
    def get_models(self) -> list[dict[str, str]]: ...
    def get_trained_models(self) -> dict[str, object]: ...
