"""initial tables

Revision ID: 760373e4bc3c
Revises: 
Create Date: 2026-03-20 22:54:08.027255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '760373e4bc3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_store',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('state', JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('interrupt_ids', JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('chat_threads',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('has_training_context', sa.Boolean(), nullable=False),
    sa.Column('training_context_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('training_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_job_id', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=True),
    sa.Column('model_type', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('target_column', sa.String(length=128), nullable=True),
    sa.Column('metrics', JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('linked_datasets', JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('model_preference', sa.String(length=128), nullable=True),
    sa.Column('state', JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_table('training_contexts')
    op.drop_table('chat_threads')
    op.drop_table('agent_store')
    # ### end Alembic commands ###
